services:
  front:
    build:
      context: ../../front_end
      dockerfile: ./Dockerfile.dev
    depends_on:
      - back
    container_name: front
    networks:
      - public
    ports:
      - "4173:4173"
    restart: unless-stopped

  back:
    build:
      context: ../../back_end
      dockerfile: ./Dockerfile.back
    depends_on:
      - redis
    container_name: back
    env_file:
      - .env.dev
    networks:
      - public
      - isolated
    volumes:
      - ./config/google_client_secret.json:/app/config/google_client_secret.json:ro
    restart: unless-stopped

  redis:
    image: redis:alpine3.22
    container_name: redis
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - isolated
    volumes:
      - fb_dev_redis_data:/data:rw
      - ./config/redis.dev.conf:/usr/local/etc/redis/redis.conf
    restart: unless-stopped

volumes:
  fb_dev_redis_data:

networks:
  isolated:
    driver: bridge
    internal: true
  public:
    driver: bridge